export const ApiRoute=import.meta.env.VITE_ROUTE_API
export const MonedaRoute=ApiRoute+'/monedas'
export const LoginRoute=ApiRoute+'/usuario/login'
export const AreaRoute = ApiRoute + "/areas";
export const DocumentoRoute = ApiRoute + "/documentos";
export const FormaPagoRoute = ApiRoute + "/forma-pago";
export const TipoServicioRoute = ApiRoute + "/tipo-servicio";
export const ComboRoute = ApiRoute + "/combo";
export const ClientesRoute = ApiRoute + "/clientes";
export const ProyectosRoute = ApiRoute + "/proyectos";
export const CargarDocumentosRoute = ApiRoute + "/cargar-documentos";
export const UsuarioRoute = ApiRoute + "/usuario";
export const CotizacionRoute = ApiRoute + "/cotizaciones";
export const VouchersRoute = ApiRoute + "/vouchers";
export const FacturacionRoute = ApiRoute + "/facturacion";
export const DebtPaymentRoute = ApiRoute + "/debt-payment";
export const ReportRoute = ApiRoute + "/report";
export const FolderRoute = ApiRoute + "/folder";
export const FilesRoute = ApiRoute + "/files";
export const RolePermisosRoute = ApiRoute + "/roles";
export const MenuRoute = ApiRoute + "/menu";
export const UserRoute = ApiRoute + "/usuarios";
//**
export const TipoVehiculoRoute = ApiRoute + "/tipo-vehiculos";
export const MarcaRoute = ApiRoute + "/marcas";
export const ModelosRoute = ApiRoute + "/modelos";
export const CombustibleRoute = ApiRoute + "/combustible";
export const GruposRoute = ApiRoute + "/grupo";
export const VehiculosRoute = ApiRoute + "/vehiculos";
