export const MENU = [
  {
    clases: "",
    color: "",
    css: "",
    descripcion: "Dashboard",
    icono: "fas fa-home",
    nombre: "Dashboard",
    url: "/dashboard",
    slug: "dashboard",
    submenus: [],
  },
  {
    clases: "",
    color: "",
    css: "",
    descripcion: "Maestros",
    icono: "fas fa-edit",
    nombre: "Forms",
    url: "/maestros",
    submenus: [
      {
        descripcion: "Tipo Vehiculos",
        icono: "",
        nombre: "tipo vehiculos",
        url: "tipo-vehiculos",
        slug: "tipo-vehiculos",
      },
      {
        descripcion: "Marcas",
        icono: "",
        nombre: "marcas",
        url: "marcas",
        slug: "marcas",
      },
      {
        descripcion: "Modelos",
        icono: "",
        nombre: "modelos",
        url: "modelos",
        slug: "modelos",
      },
      {
        descripcion: "Vehiculos",
        icono: "",
        nombre: "vehiculos",
        url: "vehiculos",
        slug: "vehiculos",
      },
      {
        descripcion: "Combustible",
        icono: "",
        nombre: "combustible",
        url: "combustible",
        slug: "combustible",
      },
      {
        descripcion: "Grupo",
        icono: "",
        nombre: "grupo",
        url: "grupo",
        slug: "grupo",
      },
    ],
  },
  {
    clases: "",
    color: "",
    css: "",
    descripcion: "Accesos",
    icono: "fas fa-shield",
    nombre: "Accesos",
    url: "/accesos",
    submenus: [
      {
        descripcion: "Usuarios",
        icono: "",
        nombre: "usuarios",
        url: "usuarios",
        slug: "usuarios",
      },
      {
        descripcion: "Roles y Permisos",
        icono: "",
        nombre: "roles",
        url: "roles",
        slug: "roles-permisos",
      },
    ],
  },
];
